#!/bin/bash

# STARTUP
sxhkd &
polybar example &
picom &
nitrogen --restore &
pulseaudio &
xsetroot -cursor_name left_ptr &

# WORKSPACES
bspc monitor -d 1 2 3 4 5

# BORDERS
bspc config border_width 1
bspc config window_gap 15

bspc config normal_border_color		"#101010"
bspc config active_border_color		"#525252"
bspc config focused_border_color	"#72009c"

# PRESELECT COLOR
bspc config presel_feedback_color	"#600078"

# SPLIT SIZE
bspc config split_ratio		0.52

# FOCUS WITH POINTER
bspc config focus_follows_pointer true
bspc config pointer_modifier super

# WINDOW RULES
bspc rule -a firefox state=floating rectangle=1280x720+70+90
